// web/src/pages/home/home.tsx
import { useNavigate } from 'react-router-dom'
import './home.css'

const menuItems = [
  { id: 1, content: '自动关机部署', path: '/shutdown' },
  { id: 2, content: '网易云听歌记录', path: '/history' },
  { id: 3, content: '编辑器', path: '/markdown' },
  { id: 4, content: '更多功能，敬请期待...' }
]

export default function Home() {
  const navigate = useNavigate()

  return (
    <div className="home-container">
      <ul className="grid-menu">
        {menuItems.map((item) => (
          <li key={item.id} onClick={() => item.path && navigate(item.path)}>
            <span className="grid-content">{item.content}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}

// web-angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  menuItems = [
    { index: 1, content: '自动关机部署', itemFunction: () => { this.router.navigateByUrl('shutdown') } },
    { index: 2, content: '网易云听歌记录', itemFunction: () => { this.router.navigateByUrl('history') } },
    { index: 3, content: 'Markdown', itemFunction: () => { this.router.navigateByUrl('markdown') } },
    { index: 4, content: '更多功能，敬请期待...' }
  ]

  constructor(private router: Router) { 
    this.router = router
  }

  ngOnInit(): void {
  }
}

<div>
  <ul class="grid-menu">
    <li *ngFor="let item of menuItems" (click)="item.itemFunction">
      <span class="grid-content">{{ item.content }}</span>
    </li>
  </ul>
</div>
